language: python
sudo: required
dist: trusty

branch:
    except:
        - pdf

install:
    # python
    - pip install pygments ghp-import
    # TeXLive
    - curl -sSL https://gist.githubusercontent.com/seisman/ad00252a9f03fc644146a11e6983d9c5/raw/install-tl.sh -o install-tl.sh
    - sudo bash install-tl.sh
    - source ~/.bash_profile
    - export TLMGR=`which tlmgr`
    - sudo $TLMGR update --self --all -repository http://ctan.sharelatex.com/tex-archive/systems/texlive/tlnet/
    - sudo $TLMGR install tracklang siunitx symbol

script:
    make

deploy:
    skip_cleanup: true
    provider: script
    script: ./.travis-deploy.sh
    on:
        branch: master
