language: python
sudo: required
dist: trusty

branch:
    except:
        - pdf

install:
    # python
    - pip install pygments
    - sudo bash install-tl.sh
    - source ~/.bash_profile
    - export TLMGR=`which tlmgr`
    - sudo $TLMGR update --self --all -repository http://ctan.sharelatex.com/tex-archive/systems/texlive/tlnet/
    - sudo $TLMGR install tracklang siunitx symbol

script:
    make
    mkdir tmpdir
    cp SAC_Docs.pdf tmpdir/

deploy:
    provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    target-branch: pdf
    on:
        branch: master
